#!/bin/bash
testwith() {
    echo Testing in $1

    docker run -it --rm \
        --mount "type=bind,source=$HOME/.m2,destination=/root/.m2,readonly" \
        --mount "type=bind,source=$(pwd),destination=/root/source,readonly" \
        -w /root/work \
        $1  \
         /bin/bash -c "cp -r /root/source/* /root/work/ && mvn clean test"
}

set -e
testwith maven:3-jdk-8 
testwith maven:3-jdk-9
testwith maven:3-jdk-10
testwith maven:3-jdk-11
testwith maven:3-jdk-12
testwith maven:3-jdk-13
testwith maven:3-amazoncorretto-8
testwith maven:3-amazoncorretto-11

